### ISSUE TITLE
Pre-populate data before wallet is connected

### ISSUE THREAD

**Issue by mhluongo** [saddle-finance/saddle-frontend#276] opened 2021-01-24 02:31 UTC
Here's an example on the deposit page, prior connecting my wallet.

![Screenshot from 2021-01-23 21-27-55](https://user-images.githubusercontent.com/427505/105619602-3d650000-5dc2-11eb-80b9-553c6edd961a.png)

Ethers has a [default provider](https://docs.ethers.io/v5/api/providers/) that should be a good fit and can be loaded with the app.

**Comment by alphastorm** [comment] 2021-01-24 21:42
Duplicate of #264

**Closed by alphastorm** 2021-01-24 21:42 UTC
